[build]
    publish = "dist/"
    command = "ELEVENTY_ENV=prod eleventy"

[[headers]]
    for = "/*.jpg"
    [headers.values]
        cache-control = '''
        public,
        max-age=31536000,
        immutable'''

[[headers]]
    for = "/*.png"
    [headers.values]
        cache-control = '''
        public,
        max-age=31536000,
        immutable'''

[[headers]]
    for = "/*.css"
    [headers.values]
        cache-control = '''
        public,
        max-age=31536000,
        immutable'''

[[headers]]
    for = "/*.js"
    [headers.values]
        content-type = "application/javascript; charset=utf-8"
        
[[headers]]
    for = "/*"
    [headers.values]
        strict-transport-security = "max-age=31536000; includeSubDomains; preload"
        x-content-type-options = "nosniff"
        
[[headers]]
    for = "site.webmanifest"
    [headers.values]
        content-type = "application/manifest+json; charset=utf-8"
