---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: artists
  label: Artists
  create: all
  match: "**/*"
- type: document
  path: index.pug
  label: Resumé
- type: heading
  label: Projects
upload_dir: portfolio
public_path: "/portfolio"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
