[[headers]]
    for = "/*.jpg"
    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"

[[headers]
    for = "/*"
    [headers.values]
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"