name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: npm dependencies
      run: npm install
    - name: Build static site
      run: npx @11ty/eleventy
