name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present

      - name: Open Web Client Directory
        run: |
          cd ./dist
          ls -la

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          local_path: "./dist/*"
          remote_path: "/home/public/"
